#[[main]]
#  name = "Blog"
#  url = "/blog/"
#  weight = 30
[[main]]
  name = "About"
  url = "/about/"
  weight = 40
[[main]]
  name = "Contact"
  url = "/Contact/"
  weight = 50




# [[sidebar_docs]]
#   name = "Guides"
#   pageRef = "/docs/guides"
#   weight = 10
#
# [[sidebar_docs]]
#   name = "Reference"
#   pageRef = "/docs/reference"
#   weight = 20
#
# [[sidebar_docs]]
#   name = "Resources"
#   pageRef = "/docs/resources"
#   weight = 30
